# Generated by Django 2.2.12 on 2020-06-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200606_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Oczekujące', 'Oczekujące'), ('Wysłane', 'Wysłane'), ('Dostarczone', 'Dostarczone')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Systemy ochrony', 'Systemy ochrony'), ('Biuro', 'Biuro')], max_length=200, null=True),
        ),
    ]
