# Generated by Django 2.2.12 on 2020-06-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200606_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='Klient',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='Produkt',
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='data zamówienia'),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.CharField(max_length=1000, null=True, verbose_name='nota'),
        ),
    ]
