# Generated by Django 2.2.12 on 2020-06-06 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200606_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Klient',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Produkt',
            new_name='product',
        ),
    ]
